version: '2'
services:
  #container2   
  db:
    build: ./postgres/

    container_name: sistel_db
    
    expose:
      - "5432"
    ports:
      - "5432:5432"
    
    volumes: 
      - "/home/minc1/git/SisTel/src/main/resources/data:/var/www/project/sistel-db/data"

    environment:
      POSTGRES_PASSWORD: $PASSDB
      POSTGRES_USER: $USERDB 
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: $ENVDB 


  #container1
  app:
    build: ./app/

    container_name: sistel

    ports:
      - "80:8080"

    volumes: 
      - "/var/sistel/target/:/opt/jboss/wildfly/standalone/deployments/"
      - "/var/sistel/upload-dir/:/opt/jboss/upload-dir/" 
      - "/var/sistel/log/:/opt/jboss/wildfly/standalone/log/"

    environment:
      ENVDB: $ENVDB 
      USERDB: $USERDB  
      PASSDB: $PASSDB  
      LDAPURL: $LDAPURL  
      LDAPBASE: $LDAPBASE 
      LDAPUSERDN: $LDAPUSERDN  
      LDAPPASS: $LDAPPASS  
      LDAPUSERSEARCHBASE: $LDAPUSERSEARCHBASE  
      LDAPUSERSEARCHFILTER: $LDAPUSERSEARCHFILTER  
      ENVMAILHOST: $ENVMAILHOST  
      ENVMAILPORT: $ENVMAILPORT  
      ENVMAILPROTOCOL: $ENVMAILPROTOCOL  
      ENVSMTPAUTH: $ENVSMTPAUTH  
      ENVTLSENABLE: $ENVTLSENABLE  
      ENVMAILDEBUG: $ENVMAILDEBUG  
      ENVMAILTIMEOUT: $ENVMAILTIMEOUT  
      SEISERVICO: $SEISERVICO  
      SEISISTEMA: $SEISISTEMA  
      SEIURL: $SEIURL

    links:
      - "db"

