version: '2'
services:

  #container2   
  db:
    build: ./postgres/

    container_name: sistel_db
    
    expose:
      - "5432"
    ports:
      - "5432:5432"
    
    volumes: 
      - /home/minc1/git/SisTel/src/main/resources/data:/var/www/project/sistel-db/data

    env_file:
      - app-variables.env

  #container1
  app:
    build: ./app/

    container_name: sistel

    ports:
      - "80:8080"

    volumes: 
      - /var/sistel/target/:/opt/jboss/wildfly/standalone/deployments/
      - /var/sistel/upload-dir/:/opt/jboss/upload-dir/
      - /var/sistel/log/:/opt/jboss/wildfly/standalone/log/

    env_file:
      - app-variables.env

    links:
      - "db"

